package com.wedspot.backend.Model.Entity;

import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDateTime;

@Entity
@Data
@Table(name = "\"users\"")
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Match 'generated by default as identity'
    @Column(name = "\"ID\"") // Match the double-quoted uppercase ID in SQL
    private Long id;

    @Column(name = "\"NAME\"")
    private String name;

    @Column(name = "\"EMAIL\"")
    private String email;

    @Column(name = "\"PASSWORD\"")
    private String password;

    @Column(name = "\"ROLE\"")
    private String role;

    @Column(name = "\"PHONE_NUMBER\"")
    private String phoneNumber;

    @Column(name = "\"ADDRESS\"")
    private String address;

    @Column(name = "\"ENABLED\"")
    private boolean enabled = true;

    @Column(name = "\"CREATED_AT\"")
    private LocalDateTime createdAt;

    @Column(name = "\"UPDATED_AT\"")
    private LocalDateTime updatedAt = LocalDateTime.now();

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

}
